name: build

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

env:
  LM_LICENSE_FILE: "$GITHUB_WORKSPACE/tools/mwccarm/license.dat"
  CC: gcc-10
  CXX: g++-10
  CALCROM_DISCORD_WEBHOOK_AVATAR_URL: "https://i.imgur.com/38BQHdd.png"
  CALCROM_DISCORD_WEBHOOK_USERNAME: OK
  CALCROM_WEBHOOK_URL: ${{ secrets.WEBHOOKURL }}

jobs:
  build-heartgold:
    runs-on: ubuntu-22.04

    steps:
      - name: Update and Install Software
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt update
          sudo apt -y --allow-downgrades install g++-10-multilib linux-libc-dev binutils-arm-none-eabi p7zip-full pkg-config libpugixml-dev ppa-purge
          sudo ppa-purge -y ppa:ubuntu-toolchain-r/test || true
          sudo dpkg --add-architecture i386
          sudo mkdir -pm755 /etc/apt/keyrings
          sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
          sudo add-apt-repository ppa:cybermax-dexter/sdl2-backport
          sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/$(lsb_release -cs)/winehq-$(lsb_release -cs).sources
          sudo apt update
          sudo apt -y --allow-downgrades install --install-recommends winehq-stable

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build ROM
        env:
          GAME_VERSION: SOULSILVER
          GAME_LANGUAGE: ENGLISH
          GAME_REVISION: 0
          NONMATCHING: 0
          COMPARE: 1
          BUILD_OUT: build/soulsilver.us/
        uses: ./.github/workflows/build-rom

  build-nonmatching-heartgold:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build ROM
        env:
          GAME_VERSION: HEARTGOLD
          GAME_LANGUAGE: ENGLISH
          GAME_REVISION: 0
        run: make -j4

  build-nonmatching-soulsilver:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build ROM
        env:
          GAME_VERSION: SOULSILVER
          GAME_LANGUAGE: ENGLISH
          GAME_REVISION: 0
        run: make -j4

      - name: Webhook
        run: |
          sudo chmod 755 $GITHUB_WORKSPACE/.github/calcrom/webhook.sh
          $GITHUB_WORKSPACE/.github/calcrom/webhook.sh pokeheartgold "$CALCROM_WEBHOOK_URL"
        continue-on-error: true

      - name: Checkout xMAP
        uses: actions/checkout@v4
        with:
          path: 'xmap'
          ref: 'xmap'

      - name: Move xMAP
        run: |
          mkdir -p xmap
          cp build/heartgold.us/*.xMAP xmap/heartgoldus.xMAP
          cp build/soulsilver.us/*.xMAP xmap/soulsilverus.xMAP
          echo "XMAP_COMMIT_MSG=$( git log --format=%s ${GITHUB_SHA} )" >> $GITHUB_ENV

      - name: Update xMAP
        uses: EndBug/add-and-commit@v9
        with:
          cwd: "./xmap"
          add: "*.xMAP"
          message: ${{ env.XMAP_COMMIT_MSG }}
